dist: trusty
sudo: true

language: python
python:
  - '3.5'

env:
  global:
    - SOLC_URL='https://github.com/ethereum/solidity/releases/download/v0.4.13/solc-static-linux'
    - SOLC_VERSION='v0.4.13'
  matrix:
    - TEST_TYPE='microraiden'
    - TEST_TYPE='contracts'

before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - ./.travis/download_solc.sh

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip wheel coveralls "coverage<4.4"
  - pip install pytest-travis-fold
  - pip install flake8
  - pip install -r microraiden/requirements.txt

before_script:
  - flake8 microraiden/

script:
  - coverage run --source microraiden/ --omit 'microraiden/microraiden/test/*,microraiden/microraiden/examples/*' -m py.test -k-needs_xorg --travis-fold=always -vvvvvv $TEST_TYPE

after_success:
  - coveralls

